channels:
  - defaults
  - setuptools
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.10
  - snakemake=7.8.1
  - cookiecutter=1.7.3
  - pathlib=1.0.1
  - pandas=1.4.2
  - ipython=8.3.0
  - pandoc=2.18
  - tabulate=0.8.10
