---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(reshape2)
library(tibble)
library(ggpubr)
```

```{r}
phenodata <- as.data.frame(fread("/Users/aladyeva.e/Dropbox (ArtyomovLab)/GTEx_lung/GTEx_sample_attributes_and_subject_lung.tsv"))

for (dataset_ in c(
                   "GTEX_LUNGS_F_HK_CC_TOP12000_X","GTEX_LUNGS_F_HK_CC_TOP12000_Rand",
                   "GTEX_LUNGS_F_HK_CC_TOP12000_Cntr","GTEX_LUNGS_F_HK_CC_TOP12000_Omega")) {
  print(dataset_)
  for (ct in 3:10) {
    print(ct)
    DATA_DIR <- paste0("/Volumes/martyomov/Active/IndividualBackUps/aladyevae/deconvolution/data/results/",dataset_,"/08_2022/ct",ct)
    DATA_DIR <- file.path(list.files(DATA_DIR,full.names = T)[1],"best")
    if (dir.exists(DATA_DIR)) {
      load(file.path(DATA_DIR,"metafile.meta"))
    colnames(metadata_$full_proportions) <- colnames(metadata_$V_row)    
    toPlot <- melt(metadata_$full_proportions)
    colnames(toPlot) <- c("Cell_type","Sample","Proportions")
    toPlot <- merge(x=toPlot,y=phenodata,by.x=c("Sample"),by.y = c("SAMPID"),all.x=TRUE)
    toPlot <- toPlot[,c("Sample","Cell_type","Proportions","SEX","AGE")]
    toPlot$AGE <- as.factor(toPlot$AGE)
    toPlot$SEX <- as.factor(toPlot$SEX)
    toPlot$Cell_type <- as.factor(toPlot$Cell_type)
    
    p <- ggviolin(data = toPlot, x="AGE", y="Proportions", color = "Cell_type", 
              fill="Cell_type", palette = "npg", 
             add = "mean_sd", add.params = list(color = "black", size=0.2))
    p <- facet(p + theme_bw(), facet.by = "Cell_type",
          nrow=3, strip.position = "right")
    my_comparisons <- list( c("20-29", "70-79"))
    dir.create(file.path(DATA_DIR,"pheno"),showWarnings = F,recursive = T)
    
    p <- p + stat_compare_means(comparisons = my_comparisons, label = "p.signif",
                                vjust=1.5) + 
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
    ggsave(filename = file.path(DATA_DIR,"pheno","age.png"),
           device="png",width = 6, height = 4)
    
    
    p <- ggviolin(data = toPlot, x="SEX", y="Proportions", color = "Cell_type", 
          fill="Cell_type", palette = "npg", 
         add = "mean_sd", add.params = list(color = "black", size=0.2))
    p <- facet(p + theme_bw(), facet.by = "Cell_type",
          nrow=3, strip.position = "right")
    my_comparisons <- list( c("1", "2"))
    p <- p + stat_compare_means(comparisons = my_comparisons, label = "p.signif",
                                vjust=1)
    ggsave(filename = file.path(DATA_DIR,"pheno","sex.png"),
           device="png",width = 4, height = 6)
    } else {
      print(paste(DATA_DIR," does not exist"))
    }
    
  }
  
}

```




